
package ventanas;

import clases.AgregarImagen;
import clases.Conexion;
import com.mysql.jdbc.EscapeTokenizer;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static ventanas.Ventana_Administrador.Apellidos;
import static ventanas.Ventana_Administrador.Cargo;
import static ventanas.Ventana_Administrador.DNI;
import static ventanas.Ventana_Administrador.FechaDeIngreso;
import static ventanas.Ventana_Administrador.H_Ingreso;
import static ventanas.Ventana_Administrador.Nombre;
import static ventanas.Ventana_Administrador.estado;

/**
 *
 * @author Usuario
 */
public class AsistenciaEmpleados extends javax.swing.JInternalFrame {

    public static String Nombre,Apellidos,Cargo,DNI,H_Ingreso,F_Ingreso,FechaUpdateAsistencia;
    public static int horaIngresoAS;
    public AsistenciaEmpleados() {
        initComponents();
        this.setResizable(false);
        setLocation(250, 50);// interfaz centrada
     
         // Recuperar datos de el login
        Nombre=Login.Nombre;
        Apellidos=Login.Apellidos;
        Cargo=Login.Cargo;
        DNI=Login.DNI;
        F_Ingreso=Login.FechaDeIngreso;
        H_Ingreso=Login.H_Ingreso;
        
            // enviamos los datos a los label
    jLabel_Nombre.setText(Nombre.toLowerCase());
    jLabel_Apellidos.setText(Apellidos.toLowerCase());
    jLabel_Cargo.setText(Cargo.toLowerCase()); ;
    jLabel_Dni.setText(DNI.toLowerCase());
    jLabel_F_de_ingreso.setText(F_Ingreso.toLowerCase());
    jLabel_H_de_ingreso.setText(H_Ingreso.toLowerCase());

    
       // hora de salida generada automatcamente 
       Calendar calendario = Calendar.getInstance();
        horaIngresoAS = calendario.get(Calendar.HOUR_OF_DAY);

               FechaUpdateAsistencia=F_Ingreso;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        boton_registroAsistencias = new javax.swing.JButton();
        boton_ReporteAsistencias = new javax.swing.JButton();
        boton_salir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel_Nombre = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel_Apellidos = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel_Dni = new javax.swing.JLabel();
        jLabel_Cargo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel_H_de_ingreso = new javax.swing.JLabel();
        jLabel_F_de_ingreso = new javax.swing.JLabel();
        ImagenUser = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        jLabel1.setText("jLabel1");

        boton_registroAsistencias.setBackground(new java.awt.Color(153, 153, 153));
        boton_registroAsistencias.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        boton_registroAsistencias.setForeground(new java.awt.Color(255, 255, 255));
        boton_registroAsistencias.setText("Registrar Asistencia");
        boton_registroAsistencias.setBorder(null);
        boton_registroAsistencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_registroAsistenciasActionPerformed(evt);
            }
        });

        boton_ReporteAsistencias.setBackground(new java.awt.Color(153, 153, 153));
        boton_ReporteAsistencias.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        boton_ReporteAsistencias.setForeground(new java.awt.Color(255, 255, 255));
        boton_ReporteAsistencias.setText("Reporte de Asistencias");
        boton_ReporteAsistencias.setBorder(null);
        boton_ReporteAsistencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_ReporteAsistenciasActionPerformed(evt);
            }
        });

        boton_salir.setBackground(new java.awt.Color(102, 102, 102));
        boton_salir.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        boton_salir.setForeground(new java.awt.Color(255, 255, 255));
        boton_salir.setText("Cerrar");
        boton_salir.setBorder(null);
        boton_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_salirActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Nombre:");

        jLabel_Nombre.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel_Nombre.setForeground(new java.awt.Color(0, 102, 102));
        jLabel_Nombre.setText("asf");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Apellidos:");

        jLabel_Apellidos.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel_Apellidos.setForeground(new java.awt.Color(0, 102, 102));
        jLabel_Apellidos.setText("asf");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("DNI:");

        jLabel_Dni.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel_Dni.setForeground(new java.awt.Color(0, 102, 102));
        jLabel_Dni.setText("asf");

        jLabel_Cargo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Cargo.setForeground(new java.awt.Color(0, 102, 102));
        jLabel_Cargo.setText("asf");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Cargo:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Hora de Ingreso:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Fecha de Ingreso:");

        jLabel_H_de_ingreso.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel_H_de_ingreso.setForeground(new java.awt.Color(0, 102, 102));
        jLabel_H_de_ingreso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_H_de_ingreso.setText("asf");

        jLabel_F_de_ingreso.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel_F_de_ingreso.setForeground(new java.awt.Color(0, 102, 102));
        jLabel_F_de_ingreso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_F_de_ingreso.setText("asf");

        ImagenUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagenEmpleado.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(34, 34, 34)
                                .addComponent(jLabel_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel4))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_Cargo, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel_Apellidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel_Dni, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel_H_de_ingreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel_F_de_ingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(boton_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ImagenUser, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(boton_registroAsistencias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boton_ReporteAsistencias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel_Dni, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Cargo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_H_de_ingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel_F_de_ingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(ImagenUser, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(boton_registroAsistencias, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_ReporteAsistencias, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_salirActionPerformed
        
        
        this.dispose();
    }//GEN-LAST:event_boton_salirActionPerformed

    private void boton_registroAsistenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_registroAsistenciasActionPerformed
       String dniEmpleado="",id_contratoUsuario="";int horaDeSalida=0, horasTrabajadas = 0;
       
 
      try {  Connection cn2=Conexion.Conectar();
               PreparedStatement pst2= cn2.prepareStatement("Select CodigoContrato from tabla_contratos where Dni_user='"+DNI+"'");
                ResultSet resul1=pst2.executeQuery();
                if(resul1.next())
                { id_contratoUsuario=resul1.getString("CodigoContrato");cn2.close();}
        } catch (Exception e) { }
        
       try
            {
                String validarFecha="";
                Connection cn3= Conexion.Conectar();
                PreparedStatement pst3= cn3.prepareStatement("select F_asistencia from tabla_asistencias where F_asistencia='"+F_Ingreso+"'");
                ResultSet resul3=pst3.executeQuery();
                if(resul3.next())
                {
                    validarFecha=resul3.getString("F_asistencia");
                    
                    // validamos que la fecha no se repita
                    if (validarFecha.equals(F_Ingreso))
                    {
                        JOptionPane.showMessageDialog(null, "Asistencia ya Resgistrada","                           -ALERTA-",
                        JOptionPane.WARNING_MESSAGE);
                    }
                }else{
                    
               try {
               Connection cn4=Conexion.Conectar();
               PreparedStatement pst4= cn4.prepareStatement("insert into tabla_asistencias values (?,?,?,?,?,?,?)");
               pst4.setInt(1,0);
               pst4.setString(2,DNI);
               pst4.setString(3,id_contratoUsuario);
               pst4.setString(4, F_Ingreso);
               pst4.setString(5,String.valueOf(horaIngresoAS));
               pst4.setString(6,String.valueOf(horaDeSalida));
               pst4.setString(7,String.valueOf(horasTrabajadas));
               pst4.executeUpdate();
               cn4.close();
               JOptionPane.showMessageDialog(null, "Asistencia Exitosa");
               } catch (Exception e) {
                JOptionPane.showMessageDialog(null, " No se registro asistencia,contacte al administrador","ERROR",JOptionPane.WARNING_MESSAGE);
                
                System.err.println("erro, al registrar asistencia: "+e);
               }
                }
                
            } catch (SQLException ex) {}

        
    }//GEN-LAST:event_boton_registroAsistenciasActionPerformed

    private void boton_ReporteAsistenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_ReporteAsistenciasActionPerformed
       Asistencias TodasAsistencia= new Asistencias();
        TodasAsistencia.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_ReporteAsistenciasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImagenUser;
    private javax.swing.JButton boton_ReporteAsistencias;
    private javax.swing.JButton boton_registroAsistencias;
    private javax.swing.JButton boton_salir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Apellidos;
    private javax.swing.JLabel jLabel_Cargo;
    private javax.swing.JLabel jLabel_Dni;
    private javax.swing.JLabel jLabel_F_de_ingreso;
    private javax.swing.JLabel jLabel_H_de_ingreso;
    private javax.swing.JLabel jLabel_Nombre;
    // End of variables declaration//GEN-END:variables
}
