/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ventanas;
import ventanas.Ventana_Administrador;
/**
 *
 * @author Usuario
 */
public class Elegir_BoletaFactura extends javax.swing.JInternalFrame {

    /** Creates new form Elegir_BoletaFactura */
    public Elegir_BoletaFactura() {
        initComponents();
        this.setResizable(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Boton_Factura = new javax.swing.JButton();
        Boton_Boleta = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setAutoscrolls(true);
        setInheritsPopupMenu(true);
        setName(""); // NOI18N
        setOpaque(true);
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);

        Boton_Factura.setBackground(new java.awt.Color(204, 204, 255));
        Boton_Factura.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        Boton_Factura.setForeground(new java.awt.Color(255, 255, 255));
        Boton_Factura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Factura.png"))); // NOI18N
        Boton_Factura.setText("FACTURA");
        Boton_Factura.setToolTipText("Análisis de los Datos");
        Boton_Factura.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Boton_Factura.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton_Factura.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Boton_Factura.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Boton_Factura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_FacturaActionPerformed(evt);
            }
        });

        Boton_Boleta.setBackground(new java.awt.Color(204, 204, 255));
        Boton_Boleta.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        Boton_Boleta.setForeground(new java.awt.Color(255, 255, 255));
        Boton_Boleta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Boleta.png"))); // NOI18N
        Boton_Boleta.setText("BOLETA");
        Boton_Boleta.setToolTipText("Análisis de los Datos");
        Boton_Boleta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Boton_Boleta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton_Boleta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Boton_Boleta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Boton_Boleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_BoletaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Boton_Boleta, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton_Factura))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(Boton_Boleta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                .addComponent(Boton_Factura)
                .addGap(105, 105, 105))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_FacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_FacturaActionPerformed
        // TODO add your handling code here:
       ProcesoVentasFactura procesoVentasFactura= new ProcesoVentasFactura();
        Ventana_Administrador.jDesktop.add(procesoVentasFactura);
         procesoVentasFactura.setVisible(true);
       this.dispose();;
    }//GEN-LAST:event_Boton_FacturaActionPerformed

    private void Boton_BoletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_BoletaActionPerformed
        // TODO add your handling code here:
       ProcesoVentasBoleta procesoVentas= new ProcesoVentasBoleta();
       Ventana_Administrador.jDesktop.add(procesoVentas);
        procesoVentas.setVisible(true);
       this.dispose();;
    }//GEN-LAST:event_Boton_BoletaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Boleta;
    private javax.swing.JButton Boton_Factura;
    // End of variables declaration//GEN-END:variables
}
