/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.Calendar;
import javax.swing.JOptionPane;
import static ventanas.Login.FechaDeIngreso;

/**
 *
 * @author Usuario
 */
public class RegistrarClienteRucNew extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarClienteNew
     */
    int  dia, mes, año;;
    public RegistrarClienteRucNew() {
        initComponents();
        this.setResizable(false);
        setLocationRelativeTo(null);
        
        Calendar calendario = Calendar.getInstance();
        dia = calendario.get(Calendar.DATE);
        mes=calendario.get((Calendar.MONTH))+1;
        año=calendario.get(Calendar.YEAR);
     jLabel_fecha.setText(String.valueOf(dia+"/"+mes+"/"+año));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_telfCliente = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txt_correoCiente = new javax.swing.JTextField();
        txt_direcCliente = new javax.swing.JTextField();
        txt_razonCliente = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        boton_guardarCliente = new javax.swing.JButton();
        txt_rucCliente = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel_fecha = new javax.swing.JLabel();
        txt_rubroCliente1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txt_telfCliente.setBackground(new java.awt.Color(255, 255, 153));
        txt_telfCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_telfCliente.setForeground(new java.awt.Color(0, 0, 153));
        txt_telfCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txt_telfCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_telfClienteKeyTyped(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 51, 51));
        jLabel28.setText("Telf:");

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 51, 51));
        jLabel31.setText("Correo:");

        txt_correoCiente.setBackground(new java.awt.Color(255, 255, 153));
        txt_correoCiente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_correoCiente.setForeground(new java.awt.Color(0, 0, 153));
        txt_correoCiente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        txt_direcCliente.setBackground(new java.awt.Color(255, 255, 153));
        txt_direcCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_direcCliente.setForeground(new java.awt.Color(0, 0, 153));
        txt_direcCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        txt_razonCliente.setBackground(new java.awt.Color(255, 255, 153));
        txt_razonCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_razonCliente.setForeground(new java.awt.Color(0, 0, 153));
        txt_razonCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 51, 51));
        jLabel18.setText("Direccion:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 51, 51));
        jLabel17.setText("Razón Social:");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 51, 51));
        jLabel19.setText("Ruc:");

        boton_guardarCliente.setBackground(new java.awt.Color(255, 153, 0));
        boton_guardarCliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        boton_guardarCliente.setForeground(new java.awt.Color(0, 51, 51));
        boton_guardarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/usuarios.png"))); // NOI18N
        boton_guardarCliente.setText("Guardar Cliente");
        boton_guardarCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_guardarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_guardarClienteActionPerformed(evt);
            }
        });

        txt_rucCliente.setBackground(new java.awt.Color(255, 255, 153));
        txt_rucCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_rucCliente.setForeground(new java.awt.Color(204, 0, 0));
        txt_rucCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_rucCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txt_rucCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_rucClienteKeyTyped(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 51, 51));
        jLabel29.setText("Fecha:");

        jLabel_fecha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_fecha.setForeground(new java.awt.Color(0, 51, 204));
        jLabel_fecha.setText("fecha");

        txt_rubroCliente1.setBackground(new java.awt.Color(255, 255, 153));
        txt_rubroCliente1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_rubroCliente1.setForeground(new java.awt.Color(0, 0, 153));
        txt_rubroCliente1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 51, 51));
        jLabel25.setText("Rubro:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(txt_rucCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_rubroCliente1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(txt_razonCliente))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(31, 31, 31)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(177, 177, 177)
                                .addComponent(jLabel31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_correoCiente, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(txt_direcCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_telfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(boton_guardarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txt_rucCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_rubroCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txt_razonCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txt_direcCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_telfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(txt_correoCiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jLabel_fecha))
                .addGap(8, 8, 8)
                .addComponent(boton_guardarCliente)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_guardarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_guardarClienteActionPerformed
        String ruc_cliente ,razon_cliente,direccion_cliente,rubro,correoCliente,telf; int contador=0;
        // metodo para recuper la fecha selecionada de jdatechooser

        // recuperamos los valores ingresados en los jtextfield
        ruc_cliente      =txt_rucCliente.getText().trim().toUpperCase();
        razon_cliente =txt_razonCliente.getText().trim();
        direccion_cliente =txt_direcCliente.getText().trim();;
        correoCliente       =txt_correoCiente.getText().trim();
        telf   =txt_telfCliente.getText().trim();
        rubro=txt_rubroCliente1.getText().trim();
        // validamos qiue no encuentren campos en blanco
        if(ruc_cliente.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Falta ingresar  RUC ");
            txt_rucCliente.requestFocus();
            contador++;
        }
        if(razon_cliente.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Falta ingresar Razon ");
            txt_razonCliente.requestFocus();
            contador++;
        }
        if(rubro.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Falta ingresar Rubro ");
            txt_rubroCliente1.requestFocus();
            contador++;
        }
        if(direccion_cliente.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Falta ingresar Dirección ");
            txt_direcCliente.requestFocus();
            contador++;
        }
        if(telf.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Falta ingresar Teléfono");
            txt_telfCliente.requestFocus();
            contador++;
        }
     
        // si todos los campos entan llenos
        if(contador==0){
        try
        {
            Connection cn=Conexion.Conectar();
            PreparedStatement pst= cn.prepareStatement("insert into tabla_clientesruc values (?,?,?,?,?,?,?)");
            pst.setString(1,ruc_cliente);
            pst.setString(2,razon_cliente);
            pst.setString(3,rubro);
            pst.setString(4,direccion_cliente);
            pst.setString(5,telf);
            pst.setString(6,correoCliente);
            pst.setString(7,jLabel_fecha.getText());
            pst.executeUpdate();
            cn.close();
            JOptionPane.showMessageDialog(null, "Cliente Registrado Exitosamente");
            this.dispose();

        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "no se pudo registrar Cliente, contacte al administrador","",JOptionPane.ERROR_MESSAGE);
            System.err.println("error al registrar nuevo cliente: "+e);
        }
    }
        
    }//GEN-LAST:event_boton_guardarClienteActionPerformed

    private void txt_telfClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_telfClienteKeyTyped
        // TODO add your handling code here:
         char c =evt.getKeyChar();
        if(c<'0'||c>'9')evt.consume();{
            
        }
    }//GEN-LAST:event_txt_telfClienteKeyTyped

    private void txt_rucClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_rucClienteKeyTyped
        // TODO add your handling code here:
         char c =evt.getKeyChar();
        if(c<'0'||c>'9')evt.consume();{
            
        }
    }//GEN-LAST:event_txt_rucClienteKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarClienteRucNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarClienteRucNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarClienteRucNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarClienteRucNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarClienteRucNew().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_guardarCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel_fecha;
    private javax.swing.JTextField txt_correoCiente;
    private javax.swing.JTextField txt_direcCliente;
    private javax.swing.JTextField txt_razonCliente;
    private javax.swing.JTextField txt_rubroCliente1;
    private javax.swing.JTextField txt_rucCliente;
    private javax.swing.JTextField txt_telfCliente;
    // End of variables declaration//GEN-END:variables
}
